```{r data generation, echo = FALSE, results = "hide"}
n = 4
# sample(1:4,1)
p = round(runif(1,0.02,0.98),2)

mu = sum(n*p)
sig = sqrt(n*p*(1-p))

u = runif(n,0,1)
h = u>p
x = sum(h)
```

Question
========

Determine the probabilities when adding $`r n`$ spins, each with chance $`r p`$. 

<!-- Also, measure the sums of $`r n`$ spins 10 times, and report the results as a histogram.  -->

```{r wheel, echo=F,fig.height=2, fig.width=2, fig.cap=''}
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F,type='n')
thetas = 1:1000 / 1000 * 2 * pi
xs = cos(thetas)
ys = sin(thetas)
polygon(xs,ys)

lines(c(0,cos(p*2*pi)),c(0,sin(p*2*pi)))
lines(c(0,1),c(0,0),lwd=2)

text(0.8*cos(mean(c(0,p))*2*pi),0.8*sin(mean(c(0,p))*2*pi),0)
text(0.8*cos(mean(c(p,1))*2*pi),0.8*sin(mean(c(p,1))*2*pi),1)

arrows(-0.6,0,0.6,0,lwd=4,length=0.1)
```


Solution
========

Make a merging tree.

```{r mergingtree,echo=T,fig.height=2, fig.width=2, fig.cap=''}
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F,type='n')
xs = 0:n/n
x = c(0)
y = c(0.5)
for(i in 1:n){
  for(j in 1:i){
    x = c(x,i/n)
    y = c(y,mean(c(j-1,j))/i)
  }
}
points(x,y)
lines(c(0,1),c(0.5,0.5))
```


Meta-information
============
extype: string
exsolution: yo
exname: marbles
extol: 0.01
