```{r data generation, echo = FALSE, results = "hide"}
while(T){
    n = sample(4:7,1)
    x = sort(sample(1:30,n))
    l = sort(round(runif(n-1,0,1),2))
    breaks = c(0,l,1)
    p = round(breaks[2:(n+1)]-breaks[1:n],2)
    mu = sum(p*x)
    sig = sqrt(sum(p*(x-mu)^2))
    # the following requirements add considerable time...
    if(sum(p)==1 & sum(p>0.05)==n & as.integer(mu)==mu & as.integer(sig*100)==sig*100){
        break
    }
}

s = ''
for(i in 1:n){
    s = paste(s,'|',i,'|',x[i],'|',p[i],'|\n')
}

c3 = x*p
c4 = x-mu
c5 = (x-mu)^2
c6 = p*(x-mu)^2

s2 = ''
for(i in 1:n){
    s2 = paste(s2,'|',x[i],'|',p[i],'|',c3[i],'|',c4[i],'|',c5[i],'|',c6[i],'|')
    if(i < n){
        s2 = paste(s2,'\n')
    }
}

exact = sample(1:n,1)
xex = x[exact]
two = sort(sample(1:n,2))
ptwo = sum(p[two])
if(n==3){
  atlm = 2
} else {
  atlm = sample(2:(n-1),size=1)
}
xatlm = x[atlm]
atl = sample(c(T,F),1)
if(atl){
  word = "least"
  patlm = sum(p[atlm:n])
  sym = "\\ge"
} else {
  word = "most"
  patlm = sum(p[1:atlm])
  sym = "\\le"
}

```

Question
========

The spinner below will be used to generate a sample.

```{r spin, echo=F, fig.height=2, fig.width=2, fig.cap=''}
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F,type='n')
thetas = 1:1000 / 1000 * 2 * pi
xs = cos(thetas)
ys = sin(thetas)
polygon(xs,ys)
for(b in breaks){
    lines(c(0,cos(b*2*pi)),c(0,sin(b*2*pi)))
}
for(i in 1:n){
    text(0.8*cos(mean(c(breaks[i+1],breaks[i]))*2*pi),
         0.8*sin(mean(c(breaks[i+1],breaks[i]))*2*pi),x[i])
}
arrows(-0.6,0,0.6,0,lwd=4,length=0.1)
```

The spinner's probability distribution is shown below.

| $i$  | $x_i$ | $p_i$ |
|:---:|:---:|:---:|
`r s`



Answerlist
--------

* What is the probability of spinning `r xex`? In other words, what is $P(X=`r xex`)$?
* What is the probability of spinning `r x[two[1]]` or `r x[two[2]]`? In other words, what is $P(X=`r x[two[1]]` ~\text{ or }~ X=`r x[two[2]]`)$?
* If spinning twice, what is the probability of first spinning `r x[two[1]]` and then spinning `r x[two[2]]`? In other words, what is $P(X_1=`r x[two[1]]` ~\text{ and }~ X_2=`r x[two[2]]`)$?
* What is the probability of spinning at `r word` `r xatlm`? In other words, what is $P(X`r sym` `r xatlm`)$?
* Determine the mean of the probability distribution by using $\mu = \sum p_ix_i$.
* Determine the standard deviation of the probability distribution by using $\sigma = \sqrt{\sum p_i (x_i-\mu)^2}$.


Solution
========

Make a table (for parts d and e).

| $x_i$ | $p_i$ | $p_i x_i$ | $x_i-\mu$ | $(x_i-\mu)^2$ | $p_i(x_i-\mu)^2$ | 
|:---:|:---:|:---:|:---:|:---:|:---:|
`r s2`
|=========|=========|=========|=========|=========|=========|
|     |     | $\sum p_i x_i = `r mu`$ |   |   | $\sum p_i(x_i-\mu)^2 = `r sum(c6)`$   |
|     |     | $\mu = `r mu`$ |   |   | $\sigma = \sqrt{\sum p_i(x_i-\mu)^2} = `r sig`$   |

Answerlist
--------

* `r p[exact]`
* `r ptwo`
* `r p[two[1]]*p[two[2]]`
* `r patlm`
* $\mu = `r mu`$
* $\sigma = `r sig`$


Meta-information
============
extype: string
exsolution: yo
exname: marbles
extol: 0.01
