---
header-includes:
   - \usepackage{arev}
   - \usepackage{multicol}
geometry: "left=2cm,right=2cm,top=1.5cm,bottom=1cm"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

\thispagestyle{empty} 

# Confidence Interval

* The confidence level, $\gamma$, represents how confident we are the interval will contain the population parameter (population proportion or population mean).
* To get $z^{\star}$, find $z^\star$ such that $P(|Z|<z^\star)=\gamma$. To do that, first get percentile, $\ell$, from confidence level ($\gamma$):
$$\ell = \frac{\gamma+1}{2} $$
then, use the $z$-table to find $z^\star$ such that $P(Z<z^\star)=\ell$.

### Proportion

The population proportion, $p$, is estimated with an interval (to indicate uncertainty) based on a sample proportion, $\hat{p}$.

* Bounds:
$$\hat{p}\pm z^{\star}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}} $$
* Necessary sample size for a given margin of error:  
    * If $\hat{p}$ is known:
      $$n = \hat{p}(1-\hat{p})\left(\frac{z^{\star}}{ME}\right)^2 $$
    * If $\hat{p}$ is unknown, assume it is 0.5 to be conservative
      $$n = \frac{1}{4}\left(\frac{z^{\star}}{ME}\right)^2 $$

### Mean

The population mean, $\mu$, is estimated with an interval (to indicate uncertainty) based on a sample mean, $\bar{x}$.

* Bounds:
    * If $\sigma$ is known:
      $$\bar{x} \pm z^{\star} \cdot \frac{\sigma}{\sqrt{n}}$$
    * If $\sigma$ is unknown, use the sample standard deviation (and $t^{\star}$). Remember, $df = n-1$. To get $t^{\star}$, find $t^\star$ such that $P(|T|<t^\star)=\gamma$ and $df=n-1$.
      $$\bar{x} \pm t^{\star} \cdot \frac{s}{\sqrt{n}} $$
* Necessary sample size for a given margin of error:
$$n = \left( \frac{z^{\star} \sigma}{ME} \right)^2 $$


\newpage

#Hypothesis Testing (Single-Sample) 

\newcommand{\pval}{p\text{-value}}
\thispagestyle{empty}

\begin{center}
$\begin{aligned}
H_0 &= \text{null hypothesis} \\
H_A &= \text{alternative hypothesis} \\
\pval &= \text{probability of sample at least as extreme as observed, {\bf given} $H_0$} \\
\alpha &= \text{significance level = chance of type II error given $H_0$}
\end{aligned}$
\end{center}

\begin{itemize}
\item Calculate the $\pval$.
\begin{itemize}
\item "at least as extreme" can mean "as large or larger", "as small or smaller", or "as far from expected in either direction".
\end{itemize}
\item If $\pval$ is small enough, we reject the null hypothesis. (This logic is similar to {\it reductio ad absurdum} or  proof by contradiction.)
$$\text{If }~~\pval<\alpha ~~\text{ then }~~ \text{reject }H_0 $$
$$\text{If }~~\pval \ge \alpha ~~\text{ then }~~ \text{do not reject }H_0 $$
\end{itemize}

### Single-sample proportion testing

$$z_0 = \cfrac{\hat{p}-p_0}{\sqrt{\cfrac{p_0(1-p_0)}{n}}} $$

\begin{multicols}{3}
Right tail (one tail)
\begin{itemize}
\item $H_0$ claims $p = p_0$
\item $H_A$ claims $p > p_0$
\item $\pval = P(Z > z_0)$
\end{itemize}

Left tail (one tail)
\begin{itemize}
\item $H_0$ claims $p = p_0$
\item $H_A$ claims $p < p_0$
\item $\pval = P(Z < z_0)$
\end{itemize}

Two tail
\begin{itemize}
\item $H_0$ claims $p = p_0$
\item $H_A$ claims $p \ne p_0$
\item $\pval = P(|Z| > |z_0|)$
\end{itemize}
\end{multicols}

### Single-sample mean testing, $\sigma$ known

$$z_0 = \cfrac{\bar{x}-\mu_0}{\frac{\sigma}{\sqrt{n}}} $$

\begin{multicols}{3}
Right tail (one tail)
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu > \mu_0$
\item $\pval = P(Z > z_0)$
\end{itemize}

Left tail (one tail)
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu < \mu_0$
\item $\pval = P(Z < z_0)$
\end{itemize}

Two tail
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu \ne \mu_0$
\item $\pval = P(|Z| > |z_0|)$
\end{itemize}
\end{multicols}

### Single-sample mean testing, $\sigma$ unknown

$$t_0 = \cfrac{\bar{x}-\mu_0}{\frac{s}{\sqrt{n}}} $$

\begin{multicols}{3}
Right tail (one tail)
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu > \mu_0$
\item $\pval = P(T > t_0)$
\end{itemize}

Left tail (one tail)
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu < \mu_0$
\item $\pval = P(T < t_0)$
\end{itemize}

Two tail
\begin{itemize}
\item $H_0$ claims $\mu = \mu_0$
\item $H_A$ claims $\mu \ne \mu_0$
\item $\pval = P(|T| > |t_0|)$
\end{itemize}
\end{multicols}



