```{r data generation, echo = FALSE, results = "hide"}
library(latex2exp)
options(scipen=999)
while(T){
  xbar = round(runif(1,35,50),2)
  s = round(runif(1,7,15),2)
  df = sample(c(5:50,seq(55,100,5),seq(125,500,25)),1)
  n = df+1
  cls = c(0.9,0.95,0.98,0.99)
  cl = sample(cls,1)
  tstar = round(qt((cl+1)/2,df),2)
  lb = round(xbar-tstar*s/sqrt(n),2)
  ub = round(xbar+tstar*s/sqrt(n),2)
  if(ub-lb > 0.2 & lb>0){
    break
  }
}
```

Question
========

A traffic engineer wants to determine the average speed of cars on the Longfellow Bridge. She finds that a simple random sample of `r n` cars has a mean of `r xbar` mph and a standard deviation of `r s` mph. Determine a `r cl*100`% confidence interval of the average speed (in mph) of cars on the Longfellow Bridge.


Solution
========

We are given the sample size, sample mean, sample standard deviation, and confidence level.
$$
\begin{aligned}
n &= `r n` \\
\bar{x} &= `r xbar` \\
s &= `r s`\\
\gamma &= `r cl`
\end{aligned}
$$
Find the degrees of freedom.
$$\begin{aligned}
df &= n-1 \\
&= `r n`-1 \\
&= `r df`
\end{aligned}$$
Determine the critical $t$ value, $t^\star$, such that $P(|T|<t^\star) = `r cl`$ and $df=`r df`$. 
$$t^\star = `r tstar` $$
Use the formula for bounds (mean, $\sigma$ unknown).
$$
\begin{aligned}
LB &= \bar{x} - t^\star \frac{s}{\sqrt{n}} &&&&& UB &= \bar{x} + t^\star \frac{s}{\sqrt{n}} \\
   &= `r xbar` - `r tstar`\times \frac{`r s`}{\sqrt{`r n`}} &&&&&& =`r xbar` + `r tstar`\times \frac{`r s`}{\sqrt{`r n`}} \\
   &= `r lb` &&&&&&= `r ub` 
\end{aligned}
$$
We are `r cl*100`% confident that the population mean is between `r lb` and `r ub`. In this scenario, we are `r cl*100`% confident that the true average speed of cars on Longfellow is between `r lb` mph and `r ub` mph.
$$CI = (`r lb`, \, `r ub`)$$


Meta-information
============
extype: string
exsolution: (`r lb`,\,`r ub`) 
exname: mean CI
extol: 0.01
