```{r data generation, echo = FALSE, results = "hide", fig.show="hide"}
## DATA GENERATION
shape1 = 2**runif(1,-1,1)
shape2 = 2**runif(1,-1,1)
dims = sample(4:6,2)
rows = min(dims)
cols = max(dims)
n = rows*cols
offset = runif(1,0,60)
dd = round(rbeta(n,shape1,shape2)*sample(5:8,1) + offset+0.5,4)*5
data = round(dd/5)*5

## The frequency table
value = min(data/5):max(data/5) * 5
frequency = tabulate(data)[value]
df_freq = data.frame(value, frequency)
```

Question
========

Please make a frequency histogram from the following (sorted) continuous data by rounding to the nearest multiple of 5.

`r knitr::kable(t(matrix(sort(dd), nrow = rows)))`


Solution
========

Make a frequency table.

`r knitr::kable(df_freq)`

Make the histogram.

\
```{r barchart, echo = FALSE, results = "hide", fig.height = 4, fig.width = 5, fig.path = "", fig.cap = ""}
hist(dd,breaks=c(value-2.5,max(value)+2.5),main="Histogram",xlab="Value")
```
\


Meta-information
============
extype: string
exsolution: make the histogram
exname: histogram
