
```{r data generation, echo = FALSE, results = "hide"}
zs = (-3*5):(3*5)/5
ys = 0:8*0.05

z = sample((-1.4*5):(1.4*5)/5,1)

p1 = round(pnorm(z),2)
p2 = round(pnorm(z),4)

```

Question
========

The figure below shows the standard normal density. Each grid square represents 1% of probability.

```{r gridnorm,echo=F,fig.height=4,fig.width=10,fig.cap="",fig.path=paste("ug",sample(1:99999,1),sep="")}
plot(0,0,type="n",ann=F,axes=F,xlim=c(-3,3),ylim=c(0,0.4))
abline(h = ys,lty=2)
abline(v=zs,lty=2)
lines((-300:300)/100,dnorm((-300:300)/100))
axis(1,at=(-3):(3))
mtext("Z",side=1,line = 3)
lines(c(-3,3),c(0,0))
```
\

Answerlist
--------

* Estimate $z$ such that $P(Z<z) = `r p1`$ by shading and counting.
* Determine $z$ such that $P(Z<z) = `r p1`$ by using the $z$-table.


Solution
========

Answerlist
--------

* The shaded region is shown below. \newline
```{r gridnormsol,echo=F,fig.height=4,fig.width=10,fig.cap="",fig.path=paste("ug",sample(1:99999,1),sep="")}
plot(0,0,type="n",ann=F,axes=F,xlim=c(-3,3),ylim=c(0,0.4))
abline(h = ys,lty=2)
abline(v=zs,lty=2)
xs = (-300:300)/100
dn = dnorm(xs)
lines(xs,dn)
lines(c(-3,3),c(0,0))
polygon(c(xs[xs<=z],z,-3),c(dn[xs<=z],0,0),col = rgb(0.4,0.4,0.4,0.4))
axis(1,at=(-3):(3))
mtext("Z",side=1,line = 3)
```
\
\newline
When you have shaded `r round(pnorm(z),2)*100` squares, starting on the left, you should end around $z=`r z`$.
* $z \approx `r round(qnorm(p1),2)`$ 



Meta-information
============
extype: string
exsolution: yo
exname: marbles
extol: 0.01
